server:
  port: 8082
  servlet:
    context-path: /bdmp
spring:
  datasource:
    url: jdbc:mysql://47.96.143.152:3306/bdmp?useUnicode=true&characterEncoding=utf-8
    username: root
    password: Yjw970827
    driver-class-name: com.mysql.jdbc.Driver
  mvc:
    view:
      prefix: /WEB-INF/jsp/ 
      suffix: .jsp  
  quartz:
  #持久化到数据库方式
    job-store-type: jdbc #数据库方式
    jdbc:
      initialize-schema: embedded #初始化表结构
    properties:
      org:
        quartz:
          scheduler:
            instanceName: MyScheduler 
            instanceId: AUTO #默认主机名和时间戳生成实例ID,可以是任何字符串，但对于所有调度程序来说，必须是唯一的 对应qrtz_scheduler_state INSTANCE_NAME字段
          jobStore:
            class: org.quartz.impl.jdbcjobstore.JobStoreTX #持久化配置
            driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate #我们仅为数据库制作了特定于数据库的代理
            tablePrefix: QRTZ_ #使用QRTZ_作为数据库表前缀
            isClustered: true #开启集群，多个Quartz实例使用同一组数据库表
            clusterCheckinInterval: 10000 #分布式节点有效性检查时间间隔，单位：毫秒
            useProperties: false #以指示JDBCJobStore将JobDataMaps中的所有值都作为字符串，因此可以作为名称 - 值对存储而不是在BLOB列中以其序列化形式存储更多复杂的对象。从长远来看，这是更安全的，因为您避免了将非String类序列化为BLOB的类版本问题。
            dataSource: myDS
          threadPool: #连接池
            class: org.quartz.simpl.SimpleThreadPool
            threadCount: 10 #配置连接池线程数量，默认10个
            threadPriority: 5
#            threadsInheritContextClassLoaderOfInitializingThread: true
#          datasource:
#            myDS:
#              driver: com.mysql.jdbc.Driver
#              URL: jdbc:mysql://localhost:3306/quartz?serverTimezone=UTC&useSSL=false&useUnicode=true&characterEncoding=UTF-8
#              user: root
#              password: Yjw970827
#              maxConnections: 5
#mybatis: 
#  type-aliases-package:  
#  configuration:
#    call-setters-on-nulls: true 
  



